<?php
namespace classes;

/**
 * phpunit-skelgen --bootstrap ../loader.php --test -- "classes\Bash" bash.php
 * mv -v BashTest.php ../test/
 */

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-03-10 at 18:02:01.
 */
class BashTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Bash
     */
    // protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        // $this->object = new Bash;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers classes\Bash::exec
     */
    public function testExec()
    {
        $this->assertEquals(array('ahoj svete'), Bash::exec('echo "ahoj svete"', $code, $result));
        $this->assertEquals(0, $code);
        $this->assertEquals('ahoj svete', $result);
    }

    /**
     * @covers classes\Bash::isInstall
     */
    public function testIsInstall()
    {
        $this->assertTrue(Bash::isInstall('ls'));       // existuje
        $this->assertFalse(Bash::isInstall('necoSik')); // neexistuje
    }

    /**
     * @covers classes\Bash::isRoot
     */
    public function testIsRoot()
    {
        $this->assertFalse(Bash::isRoot());
    }

    /**
     * @covers classes\Bash::getTempfile
     */
    public function testGetTempfile()
    {
        $file = Bash::getTempfile();
        $this->assertFileExists($file);
        file_put_contents($file, 'ahoj data');
        $this->assertEquals('ahoj data', file_get_contents($file));
    }
}
