<?php
namespace classes;

/**
 * phpunit-skelgen --bootstrap ../loader.php --test -- "classes\ImageMaker" imagemaker.php
 * mv -v ImageMakerTest.php ../test/
 */

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-11 at 10:02:38.
 */
class ImageMakerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ImageMaker
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //~ $this->object = new ImageMaker;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        @unlink('after_thumbnail.png');
    }

    /**
     * @covers classes\ImageMaker::geometry
     */
    public function testGeometry()
    {
        $this->assertEquals(array('width' => 221, 'height' => 59), ImageMaker::geometry('logo.png'));
    }

    /**
     * @covers classes\ImageMaker::geometry
     * @expectedException classes\ExceptionImageMaker
     */
    public function testGeometry1() // size=0
    {
        ImageMaker::geometry('logo1.png');
    }

    /**
     * @covers classes\ImageMaker::geometry
     * @expectedException classes\ExceptionImageMaker
     */
    public function testGeometry2() // neexistuje
    {
        ImageMaker::geometry('logoXX.png');
    }

    /**
     * @covers classes\ImageMaker::resize
     */
    public function testResize()
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::resize('logo.png', $temp, 100, 100);
        $this->assertEquals(array('width' => 100, 'height' => 26), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::resize
     */
    public function testResize1()
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::resize('logo.png', $temp, null, null);
        $this->assertEquals(array('width' => 221, 'height' => 59), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::resize
     */
    public function testResize2()
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::resize('logo.png', $temp, 100, null);
        $this->assertEquals(array('width' => 100, 'height' => 26), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::resize
     */
    public function testResize3()
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::resize('logo.png', $temp, null, 100);
        $this->assertEquals(array('width' => 221, 'height' => 59), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::resize
     */
    public function testResize4()
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::resize('logo.png', $temp, 100, 100, true);
        $this->assertEquals(array('width' => 100, 'height' => 100), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::resize
     */
    public function testResize5()
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::resize('logo.png', $temp, 100, null, true);
        $this->assertEquals(array('width' => 100, 'height' => 26), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::resize
     */
    public function testResize6()
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::resize('logo.png', $temp, null, 100, true);
        $this->assertEquals(array('width' => 374, 'height' => 100), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::resize
     * @expectedException ImagickException
     */
    public function testResize7()
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::resize('logo.png', $temp, null, null, true);
        //~ $this->assertEquals(array('width' => 100, 'height' => 100), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::resize
     * @expectedException classes\ExceptionImageMaker
     */
    public function testResize8()
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::resize('logo1.png', $temp, null, null);
        //~ $this->assertEquals(array('width' => 100, 'height' => 100), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::resize
     * @expectedException classes\ExceptionImageMaker
     */
    public function testResize9()
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::resize('logoXX.png', $temp, null, null);
        //~ $this->assertEquals(array('width' => 100, 'height' => 100), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::resize
     */
    public function testResize10()  // vetsi zmena nez je obrazek
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::resize('logo.png', $temp, 300, 300);
        $this->assertEquals(array('width' => 221, 'height' => 59), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::resize
     */
    public function testResize11()  // vetsi zmena nez je obrazek s roztahovanim
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::resize('logo.png', $temp, 300, 300, true);
        $this->assertEquals(array('width' => 300, 'height' => 300), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::crop
     */
    public function testCrop()
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::crop('logo.png', $temp, 21, 21, 15, 25);
        $this->assertEquals(array('width' => 21, 'height' => 21), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::crop
     */
    public function testCrop1()
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::crop('logo.png', $temp, 21, 21, null, null);
        $this->assertEquals(array('width' => 21, 'height' => 21), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::crop
     */
    public function testCrop2() // vetsi nez obrazek
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::crop('logo.png', $temp, 300, 300, null, null);
        $this->assertEquals(array('width' => 221, 'height' => 59), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::crop
     */
    public function testCrop3() // mimo rozsah
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::crop('logo.png', $temp, 21, 21, 300, 300);
        $this->assertEquals(array('width' => 1, 'height' => 1), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::crop
     */
    public function testCrop4()
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::crop('logo.png', $temp, null, null, 20, 20);
        $this->assertEquals(array('width' => 201, 'height' => 39), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::crop
     * @expectedException classes\ExceptionImageMaker
     */
    public function testCrop5()
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::crop('logo1.png', $temp, 21, 21, 300, 300);
        //~ $this->assertEquals(array('width' => 1, 'height' => 1), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::crop
     * @expectedException classes\ExceptionImageMaker
     */
    public function testCrop6()
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::crop('logoXX.png', $temp, 21, 21, 300, 300);
        //~ $this->assertEquals(array('width' => 1, 'height' => 1), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::cropResize
     */
    public function testCropResize()
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::cropResize('logo.png', $temp, 50, 50);
        $this->assertEquals(array('width' => 50, 'height' => 50), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::cropResize
     */
    public function testCropResize1()
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::cropResize('logo.png', $temp, 50, null);
        $this->assertEquals(array('width' => 50, 'height' => 7), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::cropResize
     */
    public function testCropResize2()
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::cropResize('logo.png', $temp, null, 50);
        $this->assertEquals(array('width' => 94, 'height' => 50), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::cropResize
     * @expectedException ImagickException
     */
    public function testCropResize3()
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::cropResize('logo.png', $temp, 0, 0);
        //~ $this->assertEquals(array('width' => 94, 'height' => 50), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::cropResize
     * @expectedException ImagickException
     */
    public function testCropResize4()
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::cropResize('logo.png', $temp, null, null);
        //~ $this->assertEquals(array('width' => 94, 'height' => 50), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::cropResize
     * @expectedException classes\ExceptionImageMaker
     */
    public function testCropResize5()
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::cropResize('logo1.png', $temp, 5, 5);
        //~ $this->assertEquals(array('width' => 94, 'height' => 50), ImageMaker::geometry($temp));
    }

    /**
     * @covers classes\ImageMaker::cropResize
     * @expectedException classes\ExceptionImageMaker
     */
    public function testCropResize6()
    {
        $temp = tempnam('/tmp', 'test-');
        ImageMaker::cropResize('logoXX.png', $temp, 5, 5);
        //~ $this->assertEquals(array('width' => 94, 'height' => 50), ImageMaker::geometry($temp));
    }
}
