<?php
namespace classes;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-03-03 at 12:43:33.
 */
class SitemapTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Sitemap
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Sitemap;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers classes\Sitemap::addLink
     */
    public function testAddLink()
    {
        $this->object->addLink('http://example.com')
                    ->addLink('http://example.com', '2014-01-01 12:30:50')
                    ->addLink('http://example.com', '2014-01-01 12:30:50', 'always')
                    ->addLink('http://example.com', '2014-01-01 12:30:50', 'always', 0.5);
        $this->assertEquals('<?xml version="1.0"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>http://example.com</loc></url><url><loc>http://example.com</loc><lastmod>2014-01-01T12:30:50+01:00</lastmod></url><url><loc>http://example.com</loc><lastmod>2014-01-01T12:30:50+01:00</lastmod><changefreq>always</changefreq></url><url><loc>http://example.com</loc><lastmod>2014-01-01T12:30:50+01:00</lastmod><changefreq>always</changefreq><priority>0.5</priority></url></urlset>
', $this->object->render());
    }

    /**
     * @covers classes\Sitemap::addImage
     */
    public function testAddImage()
    {
        $this->object->addLink('http://example.com')
                        ->addImage('http://example.com/image.png')
                        ->addImage('http://example.com/image.png', 'titulek obrazku')
                        ->addImage('http://example.com/image.png', 'titulek obrazku', 'caption obrazku')
                        ->addImage('http://example.com/image.png', 'titulek obrazku', 'caption obrazku', 'Limerick, Ireland')
                        ->addImage('http://example.com/image.png', 'titulek obrazku', 'caption obrazku', 'Limerick, Ireland', 'GPL 3');
        $this->assertEquals('<?xml version="1.0"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"><url><loc>http://example.com</loc><image:image><image:loc>http://example.com/image.png</image:loc></image:image><image:image><image:loc>http://example.com/image.png</image:loc><image:title>titulek obrazku</image:title></image:image><image:image><image:loc>http://example.com/image.png</image:loc><image:title>titulek obrazku</image:title><image:caption>caption obrazku</image:caption></image:image><image:image><image:loc>http://example.com/image.png</image:loc><image:title>titulek obrazku</image:title><image:caption>caption obrazku</image:caption><image:geo_location>Limerick, Ireland</image:geo_location></image:image><image:image><image:loc>http://example.com/image.png</image:loc><image:title>titulek obrazku</image:title><image:caption>caption obrazku</image:caption><image:geo_location>Limerick, Ireland</image:geo_location><image:license>GPL 3</image:license></image:image></url></urlset>
', $this->object->render());
    }

    /**
     * @covers classes\Sitemap::render
     */
    public function testRender()
    {
        $this->assertEquals('<?xml version="1.0"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"/>
', $this->object->render());

        $this->object->addLink('http://example.com')
                        ->addImage('http://example.com/image.png');
        $this->assertEquals('<?xml version="1.0"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"><url><loc>http://example.com</loc><image:image><image:loc>http://example.com/image.png</image:loc></image:image></url></urlset>
', $this->object->render());
    }
}
