#! /bin/bash
#by geniv

REPO=$1
SVNPATH="/var/www/www/svn"
SVNLOG="php /var/www/gfdesign.cz/svn/log.php"

POSTCOMMIT="#!/bin/bash\n#generated by geniv\nREPOS="\$1"\nREV="\$2"\n\n${SVNLOG} "\$REV" "\$REPOS""

if [ "${REPO}" == "" ]; then
    echo "pridavani svn repozitare, pouziti:"
    echo "sudo $0 <cestaRepozitrare>"
    echo "napr: sudo $0 apps/projekt1X"
    exit 0
fi

if [ "${REPO}" != "" ] && ! [ -d $SVNPATH/$REPO ]; then
    # vytvareni adresaru, vytvari se uz pod www-data
    mkdir -v -m +x -p $SVNPATH/$REPO
    #cd $( dirname $SVNPATH/$REPO )
    #chmod -vR 0777 $( basename $SVNPATH/$REPO )

    echo "svnadmin vytvari $REPO"
    svnadmin create $SVNPATH/$REPO

    echo "nastavuju post-commit hooks"
    echo -e $POSTCOMMIT > $SVNPATH/$REPO/hooks/post-commit

    echo "nastavuji prava"
    chmod -v +x $SVNPATH/$REPO/hooks/post-commit
fi