--programming by Geniv
set animate on

select $Dummy01
sliderTime = 200
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 250
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 650
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 700
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 1100
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 1150
rotate $ (angleaxis 120 [0,0,1])--otáèení

select $Dummy02
sliderTime = 205
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 255
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 655
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 705
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 1105
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 1155
rotate $ (angleaxis 120 [0,0,1])--otáèení

select $Dummy03
sliderTime = 210
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 260
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 660
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 710
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 1110
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 1160
rotate $ (angleaxis 120 [0,0,1])--otáèení

select $Dummy04
sliderTime = 215
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 265
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 665
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 715
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 1115
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 1165
rotate $ (angleaxis 120 [0,0,1])--otáèení

select $Dummy05
sliderTime = 220
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 270
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 670
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 720
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 1120
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime =1170
rotate $ (angleaxis 120 [0,0,1])--otáèení

select $Dummy06
sliderTime = 225
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 275
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 675
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 725
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 1125
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 1175
rotate $ (angleaxis 120 [0,0,1])--otáèení

select $Dummy07
sliderTime = 230
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 280
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 680
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 730
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 1130
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 1180
rotate $ (angleaxis 120 [0,0,1])--otáèení

select $Dummy08
sliderTime = 235
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 285
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 685
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 735
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 1135
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 1185
rotate $ (angleaxis 120 [0,0,1])--otáèení

select $Dummy09
sliderTime = 240
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 290
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 690
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 740
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 1140
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 1190
rotate $ (angleaxis 120 [0,0,1])--otáèení

select $Dummy10
sliderTime = 245
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 295
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 695
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 745
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 1145
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 1195
rotate $ (angleaxis 120 [0,0,1])--otáèení

select $Dummy11
sliderTime = 250
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 300
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 700
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 750
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 1150
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 1200
rotate $ (angleaxis 120 [0,0,1])--otáèení

select $Dummy12
sliderTime = 255
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 305
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 705
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 755
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 1155
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 1205
rotate $ (angleaxis 120 [0,0,1])--otáèení

select $Dummy13
sliderTime = 260
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 310
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 710
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 760
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 1160
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 1210
rotate $ (angleaxis 120 [0,0,1])--otáèení

select $Dummy14
sliderTime = 265
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 315
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 715
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 765
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 1165
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 1215
rotate $ (angleaxis 120 [0,0,1])--otáèení

select $Dummy15
sliderTime = 270
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 320
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 720
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 770
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 1170
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 1220
rotate $ (angleaxis 120 [0,0,1])--otáèení

select $Dummy16
sliderTime = 275
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 325
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 725
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 775
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 1175
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 1225
rotate $ (angleaxis 120 [0,0,1])--otáèení

select $Dummy17
sliderTime = 280
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 330
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 730
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 780
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 1180
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 1230
rotate $ (angleaxis 120 [0,0,1])--otáèení

select $Dummy18
sliderTime = 285
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 335
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 735
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 785
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 1185
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 1235
rotate $ (angleaxis 120 [0,0,1])--otáèení

select $Dummy19
sliderTime = 290
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 340
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 740
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 790
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 1190
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 1240
rotate $ (angleaxis 120 [0,0,1])--otáèení

select $Dummy20
sliderTime = 295
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 345
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 745
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 795
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 1195
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 1245
rotate $ (angleaxis 120 [0,0,1])--otáèení

select $Dummy21
sliderTime = 300
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 350
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 750
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 800
rotate $ (angleaxis 120 [0,0,1])--otáèení
sliderTime = 1200
rotate $ (angleaxis 0 [0,0,1])--èekaní
sliderTime = 1250
rotate $ (angleaxis 120 [0,0,1])--otáèení

set animate off
clearSelection()