<?php
namespace classes;

/**
 * phpunit-skelgen --test -- "classes\Message" message.php
 * mv -v MessageTest.php ../test/
 * phpunit --bootstrap ../classes/message.php MessageTest
 */

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-20 at 20:27:53.
 */
class MessageTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Message
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Message;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers classes\Message::setFrom
     * @todo   Implement testSetFrom().
     */
    public function testSetFrom()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers classes\Message::getFrom
     * @todo   Implement testGetFrom().
     */
    public function testGetFrom()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers classes\Message::addReplyTo
     * @todo   Implement testAddReplyTo().
     */
    public function testAddReplyTo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers classes\Message::setSubject
     * @todo   Implement testSetSubject().
     */
    public function testSetSubject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers classes\Message::getSubject
     * @todo   Implement testGetSubject().
     */
    public function testGetSubject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers classes\Message::addTo
     * @todo   Implement testAddTo().
     */
    public function testAddTo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers classes\Message::addCc
     * @todo   Implement testAddCc().
     */
    public function testAddCc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers classes\Message::addBcc
     * @todo   Implement testAddBcc().
     */
    public function testAddBcc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers classes\Message::setReturnPath
     * @todo   Implement testSetReturnPath().
     */
    public function testSetReturnPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers classes\Message::getReturnPath
     * @todo   Implement testGetReturnPath().
     */
    public function testGetReturnPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers classes\Message::setPriority
     * @todo   Implement testSetPriority().
     */
    public function testSetPriority()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers classes\Message::getPriority
     * @todo   Implement testGetPriority().
     */
    public function testGetPriority()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers classes\Message::setHtmlBody
     * @todo   Implement testSetHtmlBody().
     */
    public function testSetHtmlBody()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers classes\Message::getHtmlBody
     * @todo   Implement testGetHtmlBody().
     */
    public function testGetHtmlBody()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers classes\Message::addEmbeddedFile
     * @todo   Implement testAddEmbeddedFile().
     */
    public function testAddEmbeddedFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers classes\Message::addAttachment
     * @todo   Implement testAddAttachment().
     */
    public function testAddAttachment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers classes\Message::send
     * @todo   Implement testSend().
     */
    public function testSend()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers classes\Message::setMailer
     * @todo   Implement testSetMailer().
     */
    public function testSetMailer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers classes\Message::getMailer
     * @todo   Implement testGetMailer().
     */
    public function testGetMailer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers classes\Message::generateMessage
     * @todo   Implement testGenerateMessage().
     */
    public function testGenerateMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
