<?php
namespace classes;

/**
 * phpunit-skelgen --test -- "classes\Route" route.php
 * mv -v RouteTest.php ../test/
 * phpunit --bootstrap ../classes/route.php RouteTest
 */

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-06 at 17:24:36.
 */
class RouteTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $_SERVER = array('REQUEST_URI' => '/www/svn/goodflow_cook/reciped/dfsds/asdffs/ds',
                        'SCRIPT_NAME' => '/www/svn/goodflow_cook/index.php',
                        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @expectedException classes\ExceptionRoute
     */
    public function testGetUriException() {
      $r = new Route;
      $r->setRequestUri('action');
      var_dump($r->getUri());
    }

    /**
     * @covers Route::getUri
     */
    public function testGetUri()
    {
        $r = new Route();

        $this->assertEquals('reciped/dfsds/asdffs/ds', $r->getRequestUri());

        $this->assertEquals('reciped/dfsds/asdffs/ds', Route::getRequest());

        $r = new Route;

        $model = array('action/subakce/id/di/ouje');

        $this->assertEquals(array('action' => 'reciped', 'subakce' => 'dfsds', 'id' => 'asdffs', 'di' => 'ds'), $r->getUri($model));
        $this->assertEquals(array('subakce' => 'dfsds', 'id' => 'asdffs', 'di' => 'ds'), $r->getUri($model, 1));
        $this->assertEquals(array('action' => 'reciped', 'subakce' => 'dfsds'), $r->getUri($model, 0, 2));
        $this->assertEquals(array('subakce' => 'dfsds', 'id' => 'asdffs'), $r->getUri($model, 1, 2));

        $r = new Route;

        $r->setRequestUri('akce')
          ->setRouteModel($model);

        $this->assertEquals(array('action' => 'akce'), $r->getUri());

        $r->setDefaultUri('domu')
          ->setRequestUri('');

        $this->assertEquals(array('action' => 'domu'), $r->getUri());

        $r->setDefaultUri('domu/sekce1');
        $this->assertEquals(array('action' => 'domu', 'subakce' => 'sekce1'), $r->getUri());

        $r->setRouteModel(array());
        $this->assertEquals($model, $r->getRouteModel());

        $this->assertEquals(array('domu', 'sekce1'), $r->getDefaultUrl());

        $model = array('action/subakce');
        $r->setRouteModel($model)
          ->setRequestUri('pokus/sekce/dalsisekce');
        $this->assertEquals(array('action' => 'domu', 'subakce' => 'sekce1'), $r->getUri());

        $r->setRequestUri('pokus/sekce');
        $this->assertEquals(array('action' => 'pokus', 'subakce' => 'sekce'), $r->getUri());

        $this->assertEquals(array('pokus', 'sekce'), $r->getRequestUrl());

        $r->setRequestUri('pokus');
        $this->assertEquals(array('action' => 'pokus'), $r->getUri());

        $r->setRequestUri('');
        $this->assertEquals(array('action' => 'domu', 'subakce' => 'sekce1'), $r->getUri());

        $r = new Route;
        $r->setRouteModel(array('action/subakce/subsub/busbus'))
          ->setRequestUri('')
          ->setDefaultUri('');

        $this->assertEquals(array('action' => ''), $r->getUri());

        $r = new Route;
        $r->setRouteModel(array('action/subakce/subsub/busbus',
                                'action==kuksa/subjinaakce/subsub2/busbus4')
                          )
          ->setRequestUri('kuksa/franta/alojs');
        $this->assertEquals(array('action' => 'kuksa', 'subjinaakce' => 'franta', 'subsub2' => 'alojs'), $r->getUri());

        $r = new Route;
        $r->setRouteModel(array('action/subakce/subsub/busbus',
                                'action==galerie/page==[0-9]+')
                          )
          ->setRequestUri('galerie/44');
        $this->assertEquals(array('action' => 'galerie', 'page' => '44'), $r->getUri());

        // 1. chyba opravena a otestovana z provozu
        $_SERVER = array('REQUEST_URI' => '/texturepacky',
                        'SCRIPT_NAME' => '/index.php',
                        );
        $r = new Route;
        $this->assertEquals(array('action' => 'texturepacky'), $r->getUri(array('action/sekce')));
        $this->assertEquals('texturepacky', Route::getRequest()); //bugfix


        $_SERVER = array('REQUEST_URI' => '/www/git/goodflow/gmr_hosting/',
                        'SCRIPT_NAME' => '/www/git/goodflow/gmr_hosting/index.php',
                        );
        $r = new Route;
        $r->setRequestUri('');
        $this->assertEquals(array('action' => ''), $r->getUri(array('action/sekce')));
        $this->assertEquals('', Route::getRequest()); // bugfix #2
    }
}
