<?php
namespace classes;


require '../classes/xicron.php';

//classes\Tpl,

/**
 * phpunit-skelgen --test -- "classes\Tpl" tpl.php
 * mv -v TplTest.php ../test/
 * phpunit --bootstrap ../classes/tpl.php TplTest
 */

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-12-16 at 23:53:17.
 */
class XtplTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Tpl
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Tpl;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
