<?php
  $result = array("cz" => "Česky",  //popisek jazyka
                  "pl" => "Polsky",
                  "en" => "Anglicky",
                  "ano" => "Ano", //globální ano/ne
                  "ne" => "Ne",
                  "jazyk" => "Jazyk",
                  "uvod" => "Úvodní strana",
                  "informace" => "Informace",
                  "rezervace" => "Rezervace",
                  "ceny" => "Ceny",
                  "akce" => "Akce",
                  "sluzby" => "Služby",
                  "mapa_stranek" => "Mapa stránek",
                  "mapa" => "Mapa",
                  "odkazy" => "Odkazy",
                  "dokumenty" => "Dokumenty",
                  "byty" => "Domy - byty",
                  "rekreace" => "Ubytování - rekreace",
                  "ostatni" => "Nebytové prostory - ostatní",
                  "prohlaseni_o_pristupnosti" => "Prohlášení o přístupnosti",
                  "admin_webmaster" => "Administrace pro webmastery",
                  "admin_moderator" => "Administrace pro moderátory",
                  "aktuality" => "Aktuality",
                  "nadpis" => "Hostel - Ubytování - Vila  „ Anna Kail ”",
                  "vygenerovano" => "Stránka vygenerována za",
                  "reklama" => "Reklama",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "");

  return $result;
?>
