<?php
  $result = array("cz" => "Czech",  //popisek jazyka
                  "pl" => "Polish",
                  "en" => "English",
                  "ano" => "Yes", //globální ano/ne
                  "ne" => "No",
                  "jazyk" => "Language",
                  "uvod" => "Home",
                  "informace" => "Information",
                  "rezervace" => "Reservations",
                  "ceny" => "Prices",
                  "akce" => "Action",
                  "sluzby" => "Services",
                  "mapa_stranek" => "Sitemap",
                  "mapa" => "Map",
                  "odkazy" => "Links",
                  "dokumenty" => "Documents",
                  "byty" => "Houses - dwellings",
                  "rekreace" => "Accommodation - recreation",
                  "ostatni" => "Non-residential premises - other",
                  "prohlaseni_o_pristupnosti" => "Declaration of accessibility",
                  "admin_webmaster" => "Administration for webmasters",
                  "admin_moderator" => "Administration for moderators",
                  "aktuality" => "News",
                  "nadpis" => "Hostel - Accommodation - Villa  „ Anna Kail ”",
                  "vygenerovano" => "This page generated for",
                  "reklama" => "Advertising",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "");

  return $result;
?>
