<?php
  $result = array("cz" => "Czeski",  //popisek jazyka
                  "pl" => "Polski",
                  "en" => "Angielski",
                  "ano" => "Tak", //globální ano/ne
                  "ne" => "Nie",
                  "jazyk" => "Język",
                  "uvod" => "Strona główna",
                  "informace" => "Informacje",
                  "rezervace" => "Rezerwacja",
                  "ceny" => "Ceny",
                  "akce" => "Akcja",
                  "sluzby" => "Usługi",
                  "mapa_stranek" => "Sitemap",
                  "mapa" => "Mapa",
                  "odkazy" => "Linki",
                  "dokumenty" => "Dokumenty",
                  "byty" => "Domy - mieszkania",
                  "rekreace" => "Zakwaterowanie - rekreacyjny",
                  "ostatni" => "Brak lokali mieszkalnych - inne",
                  "prohlaseni_o_pristupnosti" => "Deklaracja dostępności",
                  "admin_webmaster" => "Administracja dla webmasterów",
                  "admin_moderator" => "Administracja dla moderatorów",
                  "aktuality" => "Aktualności",
                  "nadpis" => "Hostel - Zakwaterowanie - Villa  „ Anna Kail ”",
                  "vygenerovano" => "Ta strona została wygenerowana w",
                  "reklama" => "Reklama",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "",
                  "" => "");

  return $result;
?>
